// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MatModel.proto

package jp.ac.tokushima_u.is.ll.util.imgproc;

public final class MatModelProtos {
  private MatModelProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MatModelOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 cols = 1;
    /**
     * <code>required int32 cols = 1;</code>
     */
    boolean hasCols();
    /**
     * <code>required int32 cols = 1;</code>
     */
    int getCols();

    // required int32 rows = 2;
    /**
     * <code>required int32 rows = 2;</code>
     */
    boolean hasRows();
    /**
     * <code>required int32 rows = 2;</code>
     */
    int getRows();

    // required int32 type = 3;
    /**
     * <code>required int32 type = 3;</code>
     */
    boolean hasType();
    /**
     * <code>required int32 type = 3;</code>
     */
    int getType();

    // repeated .serialize.MatModel.MatData datas = 4;
    /**
     * <code>repeated .serialize.MatModel.MatData datas = 4;</code>
     */
    java.util.List<jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel.MatData> 
        getDatasList();
    /**
     * <code>repeated .serialize.MatModel.MatData datas = 4;</code>
     */
    jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel.MatData getDatas(int index);
    /**
     * <code>repeated .serialize.MatModel.MatData datas = 4;</code>
     */
    int getDatasCount();
    /**
     * <code>repeated .serialize.MatModel.MatData datas = 4;</code>
     */
    java.util.List<? extends jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel.MatDataOrBuilder> 
        getDatasOrBuilderList();
    /**
     * <code>repeated .serialize.MatModel.MatData datas = 4;</code>
     */
    jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel.MatDataOrBuilder getDatasOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code serialize.MatModel}
   */
  public static final class MatModel extends
      com.google.protobuf.GeneratedMessage
      implements MatModelOrBuilder {
    // Use MatModel.newBuilder() to construct.
    private MatModel(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MatModel(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MatModel defaultInstance;
    public static MatModel getDefaultInstance() {
      return defaultInstance;
    }

    public MatModel getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MatModel(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              cols_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              rows_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              type_ = input.readInt32();
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                datas_ = new java.util.ArrayList<jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel.MatData>();
                mutable_bitField0_ |= 0x00000008;
              }
              datas_.add(input.readMessage(jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel.MatData.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          datas_ = java.util.Collections.unmodifiableList(datas_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.internal_static_serialize_MatModel_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.internal_static_serialize_MatModel_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel.class, jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel.Builder.class);
    }

    public static com.google.protobuf.Parser<MatModel> PARSER =
        new com.google.protobuf.AbstractParser<MatModel>() {
      public MatModel parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MatModel(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MatModel> getParserForType() {
      return PARSER;
    }

    public interface MatDataOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required int32 row = 1;
      /**
       * <code>required int32 row = 1;</code>
       */
      boolean hasRow();
      /**
       * <code>required int32 row = 1;</code>
       */
      int getRow();

      // required int32 col = 2;
      /**
       * <code>required int32 col = 2;</code>
       */
      boolean hasCol();
      /**
       * <code>required int32 col = 2;</code>
       */
      int getCol();

      // repeated double data = 3;
      /**
       * <code>repeated double data = 3;</code>
       */
      java.util.List<java.lang.Double> getDataList();
      /**
       * <code>repeated double data = 3;</code>
       */
      int getDataCount();
      /**
       * <code>repeated double data = 3;</code>
       */
      double getData(int index);
    }
    /**
     * Protobuf type {@code serialize.MatModel.MatData}
     */
    public static final class MatData extends
        com.google.protobuf.GeneratedMessage
        implements MatDataOrBuilder {
      // Use MatData.newBuilder() to construct.
      private MatData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private MatData(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final MatData defaultInstance;
      public static MatData getDefaultInstance() {
        return defaultInstance;
      }

      public MatData getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private MatData(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                row_ = input.readInt32();
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                col_ = input.readInt32();
                break;
              }
              case 25: {
                if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                  data_ = new java.util.ArrayList<java.lang.Double>();
                  mutable_bitField0_ |= 0x00000004;
                }
                data_.add(input.readDouble());
                break;
              }
              case 26: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                if (!((mutable_bitField0_ & 0x00000004) == 0x00000004) && input.getBytesUntilLimit() > 0) {
                  data_ = new java.util.ArrayList<java.lang.Double>();
                  mutable_bitField0_ |= 0x00000004;
                }
                while (input.getBytesUntilLimit() > 0) {
                  data_.add(input.readDouble());
                }
                input.popLimit(limit);
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
            data_ = java.util.Collections.unmodifiableList(data_);
          }
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.internal_static_serialize_MatModel_MatData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.internal_static_serialize_MatModel_MatData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel.MatData.class, jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel.MatData.Builder.class);
      }

      public static com.google.protobuf.Parser<MatData> PARSER =
          new com.google.protobuf.AbstractParser<MatData>() {
        public MatData parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new MatData(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<MatData> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required int32 row = 1;
      public static final int ROW_FIELD_NUMBER = 1;
      private int row_;
      /**
       * <code>required int32 row = 1;</code>
       */
      public boolean hasRow() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 row = 1;</code>
       */
      public int getRow() {
        return row_;
      }

      // required int32 col = 2;
      public static final int COL_FIELD_NUMBER = 2;
      private int col_;
      /**
       * <code>required int32 col = 2;</code>
       */
      public boolean hasCol() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 col = 2;</code>
       */
      public int getCol() {
        return col_;
      }

      // repeated double data = 3;
      public static final int DATA_FIELD_NUMBER = 3;
      private java.util.List<java.lang.Double> data_;
      /**
       * <code>repeated double data = 3;</code>
       */
      public java.util.List<java.lang.Double>
          getDataList() {
        return data_;
      }
      /**
       * <code>repeated double data = 3;</code>
       */
      public int getDataCount() {
        return data_.size();
      }
      /**
       * <code>repeated double data = 3;</code>
       */
      public double getData(int index) {
        return data_.get(index);
      }

      private void initFields() {
        row_ = 0;
        col_ = 0;
        data_ = java.util.Collections.emptyList();
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasRow()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasCol()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt32(1, row_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeInt32(2, col_);
        }
        for (int i = 0; i < data_.size(); i++) {
          output.writeDouble(3, data_.get(i));
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, row_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, col_);
        }
        {
          int dataSize = 0;
          dataSize = 8 * getDataList().size();
          size += dataSize;
          size += 1 * getDataList().size();
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel.MatData parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel.MatData parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel.MatData parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel.MatData parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel.MatData parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel.MatData parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel.MatData parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel.MatData parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel.MatData parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel.MatData parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel.MatData prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code serialize.MatModel.MatData}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel.MatDataOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.internal_static_serialize_MatModel_MatData_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.internal_static_serialize_MatModel_MatData_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel.MatData.class, jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel.MatData.Builder.class);
        }

        // Construct using jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel.MatData.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          row_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          col_ = 0;
          bitField0_ = (bitField0_ & ~0x00000002);
          data_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.internal_static_serialize_MatModel_MatData_descriptor;
        }

        public jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel.MatData getDefaultInstanceForType() {
          return jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel.MatData.getDefaultInstance();
        }

        public jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel.MatData build() {
          jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel.MatData result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel.MatData buildPartial() {
          jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel.MatData result = new jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel.MatData(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.row_ = row_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.col_ = col_;
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            data_ = java.util.Collections.unmodifiableList(data_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.data_ = data_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel.MatData) {
            return mergeFrom((jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel.MatData)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel.MatData other) {
          if (other == jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel.MatData.getDefaultInstance()) return this;
          if (other.hasRow()) {
            setRow(other.getRow());
          }
          if (other.hasCol()) {
            setCol(other.getCol());
          }
          if (!other.data_.isEmpty()) {
            if (data_.isEmpty()) {
              data_ = other.data_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureDataIsMutable();
              data_.addAll(other.data_);
            }
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasRow()) {
            
            return false;
          }
          if (!hasCol()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel.MatData parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel.MatData) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required int32 row = 1;
        private int row_ ;
        /**
         * <code>required int32 row = 1;</code>
         */
        public boolean hasRow() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required int32 row = 1;</code>
         */
        public int getRow() {
          return row_;
        }
        /**
         * <code>required int32 row = 1;</code>
         */
        public Builder setRow(int value) {
          bitField0_ |= 0x00000001;
          row_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 row = 1;</code>
         */
        public Builder clearRow() {
          bitField0_ = (bitField0_ & ~0x00000001);
          row_ = 0;
          onChanged();
          return this;
        }

        // required int32 col = 2;
        private int col_ ;
        /**
         * <code>required int32 col = 2;</code>
         */
        public boolean hasCol() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required int32 col = 2;</code>
         */
        public int getCol() {
          return col_;
        }
        /**
         * <code>required int32 col = 2;</code>
         */
        public Builder setCol(int value) {
          bitField0_ |= 0x00000002;
          col_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 col = 2;</code>
         */
        public Builder clearCol() {
          bitField0_ = (bitField0_ & ~0x00000002);
          col_ = 0;
          onChanged();
          return this;
        }

        // repeated double data = 3;
        private java.util.List<java.lang.Double> data_ = java.util.Collections.emptyList();
        private void ensureDataIsMutable() {
          if (!((bitField0_ & 0x00000004) == 0x00000004)) {
            data_ = new java.util.ArrayList<java.lang.Double>(data_);
            bitField0_ |= 0x00000004;
           }
        }
        /**
         * <code>repeated double data = 3;</code>
         */
        public java.util.List<java.lang.Double>
            getDataList() {
          return java.util.Collections.unmodifiableList(data_);
        }
        /**
         * <code>repeated double data = 3;</code>
         */
        public int getDataCount() {
          return data_.size();
        }
        /**
         * <code>repeated double data = 3;</code>
         */
        public double getData(int index) {
          return data_.get(index);
        }
        /**
         * <code>repeated double data = 3;</code>
         */
        public Builder setData(
            int index, double value) {
          ensureDataIsMutable();
          data_.set(index, value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated double data = 3;</code>
         */
        public Builder addData(double value) {
          ensureDataIsMutable();
          data_.add(value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated double data = 3;</code>
         */
        public Builder addAllData(
            java.lang.Iterable<? extends java.lang.Double> values) {
          ensureDataIsMutable();
          super.addAll(values, data_);
          onChanged();
          return this;
        }
        /**
         * <code>repeated double data = 3;</code>
         */
        public Builder clearData() {
          data_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:serialize.MatModel.MatData)
      }

      static {
        defaultInstance = new MatData(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:serialize.MatModel.MatData)
    }

    private int bitField0_;
    // required int32 cols = 1;
    public static final int COLS_FIELD_NUMBER = 1;
    private int cols_;
    /**
     * <code>required int32 cols = 1;</code>
     */
    public boolean hasCols() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 cols = 1;</code>
     */
    public int getCols() {
      return cols_;
    }

    // required int32 rows = 2;
    public static final int ROWS_FIELD_NUMBER = 2;
    private int rows_;
    /**
     * <code>required int32 rows = 2;</code>
     */
    public boolean hasRows() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 rows = 2;</code>
     */
    public int getRows() {
      return rows_;
    }

    // required int32 type = 3;
    public static final int TYPE_FIELD_NUMBER = 3;
    private int type_;
    /**
     * <code>required int32 type = 3;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 type = 3;</code>
     */
    public int getType() {
      return type_;
    }

    // repeated .serialize.MatModel.MatData datas = 4;
    public static final int DATAS_FIELD_NUMBER = 4;
    private java.util.List<jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel.MatData> datas_;
    /**
     * <code>repeated .serialize.MatModel.MatData datas = 4;</code>
     */
    public java.util.List<jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel.MatData> getDatasList() {
      return datas_;
    }
    /**
     * <code>repeated .serialize.MatModel.MatData datas = 4;</code>
     */
    public java.util.List<? extends jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel.MatDataOrBuilder> 
        getDatasOrBuilderList() {
      return datas_;
    }
    /**
     * <code>repeated .serialize.MatModel.MatData datas = 4;</code>
     */
    public int getDatasCount() {
      return datas_.size();
    }
    /**
     * <code>repeated .serialize.MatModel.MatData datas = 4;</code>
     */
    public jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel.MatData getDatas(int index) {
      return datas_.get(index);
    }
    /**
     * <code>repeated .serialize.MatModel.MatData datas = 4;</code>
     */
    public jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel.MatDataOrBuilder getDatasOrBuilder(
        int index) {
      return datas_.get(index);
    }

    private void initFields() {
      cols_ = 0;
      rows_ = 0;
      type_ = 0;
      datas_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasCols()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRows()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getDatasCount(); i++) {
        if (!getDatas(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, cols_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, rows_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, type_);
      }
      for (int i = 0; i < datas_.size(); i++) {
        output.writeMessage(4, datas_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, cols_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, rows_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, type_);
      }
      for (int i = 0; i < datas_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, datas_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code serialize.MatModel}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModelOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.internal_static_serialize_MatModel_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.internal_static_serialize_MatModel_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel.class, jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel.Builder.class);
      }

      // Construct using jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getDatasFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        cols_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        rows_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        if (datasBuilder_ == null) {
          datas_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          datasBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.internal_static_serialize_MatModel_descriptor;
      }

      public jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel getDefaultInstanceForType() {
        return jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel.getDefaultInstance();
      }

      public jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel build() {
        jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel buildPartial() {
        jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel result = new jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.cols_ = cols_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.rows_ = rows_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.type_ = type_;
        if (datasBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            datas_ = java.util.Collections.unmodifiableList(datas_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.datas_ = datas_;
        } else {
          result.datas_ = datasBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel) {
          return mergeFrom((jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel other) {
        if (other == jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel.getDefaultInstance()) return this;
        if (other.hasCols()) {
          setCols(other.getCols());
        }
        if (other.hasRows()) {
          setRows(other.getRows());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (datasBuilder_ == null) {
          if (!other.datas_.isEmpty()) {
            if (datas_.isEmpty()) {
              datas_ = other.datas_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureDatasIsMutable();
              datas_.addAll(other.datas_);
            }
            onChanged();
          }
        } else {
          if (!other.datas_.isEmpty()) {
            if (datasBuilder_.isEmpty()) {
              datasBuilder_.dispose();
              datasBuilder_ = null;
              datas_ = other.datas_;
              bitField0_ = (bitField0_ & ~0x00000008);
              datasBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getDatasFieldBuilder() : null;
            } else {
              datasBuilder_.addAllMessages(other.datas_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCols()) {
          
          return false;
        }
        if (!hasRows()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        for (int i = 0; i < getDatasCount(); i++) {
          if (!getDatas(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 cols = 1;
      private int cols_ ;
      /**
       * <code>required int32 cols = 1;</code>
       */
      public boolean hasCols() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 cols = 1;</code>
       */
      public int getCols() {
        return cols_;
      }
      /**
       * <code>required int32 cols = 1;</code>
       */
      public Builder setCols(int value) {
        bitField0_ |= 0x00000001;
        cols_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 cols = 1;</code>
       */
      public Builder clearCols() {
        bitField0_ = (bitField0_ & ~0x00000001);
        cols_ = 0;
        onChanged();
        return this;
      }

      // required int32 rows = 2;
      private int rows_ ;
      /**
       * <code>required int32 rows = 2;</code>
       */
      public boolean hasRows() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 rows = 2;</code>
       */
      public int getRows() {
        return rows_;
      }
      /**
       * <code>required int32 rows = 2;</code>
       */
      public Builder setRows(int value) {
        bitField0_ |= 0x00000002;
        rows_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 rows = 2;</code>
       */
      public Builder clearRows() {
        bitField0_ = (bitField0_ & ~0x00000002);
        rows_ = 0;
        onChanged();
        return this;
      }

      // required int32 type = 3;
      private int type_ ;
      /**
       * <code>required int32 type = 3;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 type = 3;</code>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>required int32 type = 3;</code>
       */
      public Builder setType(int value) {
        bitField0_ |= 0x00000004;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 type = 3;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = 0;
        onChanged();
        return this;
      }

      // repeated .serialize.MatModel.MatData datas = 4;
      private java.util.List<jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel.MatData> datas_ =
        java.util.Collections.emptyList();
      private void ensureDatasIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          datas_ = new java.util.ArrayList<jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel.MatData>(datas_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel.MatData, jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel.MatData.Builder, jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel.MatDataOrBuilder> datasBuilder_;

      /**
       * <code>repeated .serialize.MatModel.MatData datas = 4;</code>
       */
      public java.util.List<jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel.MatData> getDatasList() {
        if (datasBuilder_ == null) {
          return java.util.Collections.unmodifiableList(datas_);
        } else {
          return datasBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .serialize.MatModel.MatData datas = 4;</code>
       */
      public int getDatasCount() {
        if (datasBuilder_ == null) {
          return datas_.size();
        } else {
          return datasBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .serialize.MatModel.MatData datas = 4;</code>
       */
      public jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel.MatData getDatas(int index) {
        if (datasBuilder_ == null) {
          return datas_.get(index);
        } else {
          return datasBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .serialize.MatModel.MatData datas = 4;</code>
       */
      public Builder setDatas(
          int index, jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel.MatData value) {
        if (datasBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDatasIsMutable();
          datas_.set(index, value);
          onChanged();
        } else {
          datasBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .serialize.MatModel.MatData datas = 4;</code>
       */
      public Builder setDatas(
          int index, jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel.MatData.Builder builderForValue) {
        if (datasBuilder_ == null) {
          ensureDatasIsMutable();
          datas_.set(index, builderForValue.build());
          onChanged();
        } else {
          datasBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .serialize.MatModel.MatData datas = 4;</code>
       */
      public Builder addDatas(jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel.MatData value) {
        if (datasBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDatasIsMutable();
          datas_.add(value);
          onChanged();
        } else {
          datasBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .serialize.MatModel.MatData datas = 4;</code>
       */
      public Builder addDatas(
          int index, jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel.MatData value) {
        if (datasBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDatasIsMutable();
          datas_.add(index, value);
          onChanged();
        } else {
          datasBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .serialize.MatModel.MatData datas = 4;</code>
       */
      public Builder addDatas(
          jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel.MatData.Builder builderForValue) {
        if (datasBuilder_ == null) {
          ensureDatasIsMutable();
          datas_.add(builderForValue.build());
          onChanged();
        } else {
          datasBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .serialize.MatModel.MatData datas = 4;</code>
       */
      public Builder addDatas(
          int index, jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel.MatData.Builder builderForValue) {
        if (datasBuilder_ == null) {
          ensureDatasIsMutable();
          datas_.add(index, builderForValue.build());
          onChanged();
        } else {
          datasBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .serialize.MatModel.MatData datas = 4;</code>
       */
      public Builder addAllDatas(
          java.lang.Iterable<? extends jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel.MatData> values) {
        if (datasBuilder_ == null) {
          ensureDatasIsMutable();
          super.addAll(values, datas_);
          onChanged();
        } else {
          datasBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .serialize.MatModel.MatData datas = 4;</code>
       */
      public Builder clearDatas() {
        if (datasBuilder_ == null) {
          datas_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          datasBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .serialize.MatModel.MatData datas = 4;</code>
       */
      public Builder removeDatas(int index) {
        if (datasBuilder_ == null) {
          ensureDatasIsMutable();
          datas_.remove(index);
          onChanged();
        } else {
          datasBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .serialize.MatModel.MatData datas = 4;</code>
       */
      public jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel.MatData.Builder getDatasBuilder(
          int index) {
        return getDatasFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .serialize.MatModel.MatData datas = 4;</code>
       */
      public jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel.MatDataOrBuilder getDatasOrBuilder(
          int index) {
        if (datasBuilder_ == null) {
          return datas_.get(index);  } else {
          return datasBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .serialize.MatModel.MatData datas = 4;</code>
       */
      public java.util.List<? extends jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel.MatDataOrBuilder> 
           getDatasOrBuilderList() {
        if (datasBuilder_ != null) {
          return datasBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(datas_);
        }
      }
      /**
       * <code>repeated .serialize.MatModel.MatData datas = 4;</code>
       */
      public jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel.MatData.Builder addDatasBuilder() {
        return getDatasFieldBuilder().addBuilder(
            jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel.MatData.getDefaultInstance());
      }
      /**
       * <code>repeated .serialize.MatModel.MatData datas = 4;</code>
       */
      public jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel.MatData.Builder addDatasBuilder(
          int index) {
        return getDatasFieldBuilder().addBuilder(
            index, jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel.MatData.getDefaultInstance());
      }
      /**
       * <code>repeated .serialize.MatModel.MatData datas = 4;</code>
       */
      public java.util.List<jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel.MatData.Builder> 
           getDatasBuilderList() {
        return getDatasFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel.MatData, jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel.MatData.Builder, jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel.MatDataOrBuilder> 
          getDatasFieldBuilder() {
        if (datasBuilder_ == null) {
          datasBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel.MatData, jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel.MatData.Builder, jp.ac.tokushima_u.is.ll.util.imgproc.MatModelProtos.MatModel.MatDataOrBuilder>(
                  datas_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          datas_ = null;
        }
        return datasBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:serialize.MatModel)
    }

    static {
      defaultInstance = new MatModel(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:serialize.MatModel)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_serialize_MatModel_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_serialize_MatModel_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_serialize_MatModel_MatData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_serialize_MatModel_MatData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016MatModel.proto\022\tserialize\"\223\001\n\010MatModel" +
      "\022\014\n\004cols\030\001 \002(\005\022\014\n\004rows\030\002 \002(\005\022\014\n\004type\030\003 \002" +
      "(\005\022*\n\005datas\030\004 \003(\0132\033.serialize.MatModel.M" +
      "atData\0321\n\007MatData\022\013\n\003row\030\001 \002(\005\022\013\n\003col\030\002 " +
      "\002(\005\022\014\n\004data\030\003 \003(\001B8\n$jp.ac.tokushima_u.i" +
      "s.ll.util.imgprocB\016MatModelProtosH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_serialize_MatModel_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_serialize_MatModel_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_serialize_MatModel_descriptor,
              new java.lang.String[] { "Cols", "Rows", "Type", "Datas", });
          internal_static_serialize_MatModel_MatData_descriptor =
            internal_static_serialize_MatModel_descriptor.getNestedTypes().get(0);
          internal_static_serialize_MatModel_MatData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_serialize_MatModel_MatData_descriptor,
              new java.lang.String[] { "Row", "Col", "Data", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
